### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by edwardtiernan** [CIMM-ORG/SWMM5plus#1]
Just a test issue to see if the Github is integrated correctly onto our Slack channel

**Comment by edwardtiernan** [comment]
It worked, closing the test issue now

**Comment by bemcdonnell** [comment]
@EddieT32 where is the slack channel? is that a public one?

**Comment by edwardtiernan** [comment]
@bemcdonnell the slack channel I was referencing is one of our channels for communicating internally as a research group at UT.  I'm not sure when/if there will be a publicly available slack channel... probably once the current batch of knuckleheads moves on
